{%- set source_model = "v_stg_traffic_weather_tx" -%}
{%- set src_pk = "TRAFFIC_WEATHER_PK" -%}
{%- set src_hashdiff = "TRAFFIC_WEATHER_HASHDIFF" -%}
{%- set src_payload = ["COUNTRY",
                        "FOOT_TRAFFIC_COUNT",
                        "NUMBER_OF_LOCATIONS_DESCRIPTION",
                        "STATE",
                        "FILE_ROW_SEQ",
                        "TIMESTAMP",
                        "TIMESTAMP_INTERVAL",
                        "POSTAL_CODE",
                        "DATE_VALID_STD",
                        "DOY_STD",
                        "MIN_TEMPERATURE_AIR_2M_F",
                        "AVG_TEMPERATURE_AIR_2M_F",
                        "MAX_TEMPERATURE_AIR_2M_F",
                        "MIN_TEMPERATURE_WETBULB_2M_F",
                        "AVG_TEMPERATURE_WETBULB_2M_F",
                        "MAX_TEMPERATURE_WETBULB_2M_F",
                        "MIN_TEMPERATURE_DEWPOINT_2M_F",
                        "AVG_TEMPERATURE_DEWPOINT_2M_F",
                        "MAX_TEMPERATURE_DEWPOINT_2M_F",
                        "MIN_TEMPERATURE_FEELSLIKE_2M_F",
                        "AVG_TEMPERATURE_FEELSLIKE_2M_F",
                        "MAX_TEMPERATURE_FEELSLIKE_2M_F",
                        "MIN_TEMPERATURE_WINDCHILL_2M_F",
                        "AVG_TEMPERATURE_WINDCHILL_2M_F",
                        "MAX_TEMPERATURE_WINDCHILL_2M_F",
                        "MIN_TEMPERATURE_HEATINDEX_2M_F",
                        "AVG_TEMPERATURE_HEATINDEX_2M_F",
                        "MAX_TEMPERATURE_HEATINDEX_2M_F",
                        "MIN_HUMIDITY_RELATIVE_2M_PCT",
                        "AVG_HUMIDITY_RELATIVE_2M_PCT",
                        "MAX_HUMIDITY_RELATIVE_2M_PCT",
                        "MIN_HUMIDITY_SPECIFIC_2M_GPKG",
                        "AVG_HUMIDITY_SPECIFIC_2M_GPKG",
                        "MAX_HUMIDITY_SPECIFIC_2M_GPKG",
                        "MIN_PRESSURE_2M_MB",
                        "AVG_PRESSURE_2M_MB",
                        "MAX_PRESSURE_2M_MB",
                        "MIN_PRESSURE_TENDENCY_2M_MB",
                        "AVG_PRESSURE_TENDENCY_2M_MB",
                        "MAX_PRESSURE_TENDENCY_2M_MB",
                        "MIN_PRESSURE_MEAN_SEA_LEVEL_MB",
                        "AVG_PRESSURE_MEAN_SEA_LEVEL_MB",
                        "MAX_PRESSURE_MEAN_SEA_LEVEL_MB",
                        "MIN_WIND_SPEED_10M_MPH",
                        "AVG_WIND_SPEED_10M_MPH",
                        "MAX_WIND_SPEED_10M_MPH",
                        "AVG_WIND_DIRECTION_10M_DEG",
                        "MIN_WIND_SPEED_80M_MPH",
                        "AVG_WIND_SPEED_80M_MPH",
                        "MAX_WIND_SPEED_80M_MPH",
                        "AVG_WIND_DIRECTION_80M_DEG",
                        "MIN_WIND_SPEED_100M_MPH",
                        "AVG_WIND_SPEED_100M_MPH",
                        "MAX_WIND_SPEED_100M_MPH",
                        "AVG_WIND_DIRECTION_100M_DEG",
                        "TOT_PRECIPITATION_IN",
                        "TOT_SNOWFALL_IN",
                        "TOT_SNOWDEPTH_IN",
                        "MIN_CLOUD_COVER_TOT_PCT",
                        "AVG_CLOUD_COVER_TOT_PCT",
                        "MAX_CLOUD_COVER_TOT_PCT",
                        "MIN_RADIATION_SOLAR_TOTAL_WPM2",
                        "AVG_RADIATION_SOLAR_TOTAL_WPM2",
                        "MAX_RADIATION_SOLAR_TOTAL_WPM2",
                        "TOT_RADIATION_SOLAR_TOTAL_WPM2",
                        "ZIP",
                        "LAT",
                        "LNG",
                        "CITY",
                        "STATE_ID",
                        "STATE_NAME",
                        "ZCTA",
                        "PARENT_ZCTA",
                        "POPULATION",
                        "DENSITY",
                        "COUNTY_FIPS",
                        "COUNTY_NAME",
                        "COUNTY_WEIGHTS",
                        "COUNTY_NAMES_ALL",
                        "COUNTY_FIPS_ALL",
                        "IMPRECISE",
                        "MILITARY"] -%}
{%- set src_eff = "EFFECTIVE_FROM" -%}
{%- set src_ldts = "LOAD_DATE" -%}
{%- set src_source = "RECORD_SOURCE" -%}

{{ dbtvault.sat(src_pk=src_pk, src_hashdiff=src_hashdiff,
                src_payload=src_payload, src_eff=src_eff,
                src_ldts=src_ldts, src_source=src_source,
                source_model=source_model) }}