select EVENTID, TYPE, SEVERITY, TMC, DESCRIPTION, CONVERT_TIMEZONE( 'UTC', TIMEZONE , "StartTime(UTC)" ) as StartTime,
       CONVERT_TIMEZONE( 'UTC', TIMEZONE , "EndTime(UTC)" ) as EndTime, LOCATIONLAT, LOCATIONLNG,
       "Distance(mi)", AIRPORTCODE, NUMBER, STREET, SIDE, CITY, COUNTY, STATE, ZIPCODE from {{source ('traffic_events', 'US_TRAFFIC_EVENTS_RAW')}}