version: 2

seeds:
  - name: US_Holiday_Dates_2004_2021
    description: Holidays dates from 2004 to 2021
    columns: 
      - name: date
        description: Full date of the holiday
        tests:
          - not_null
      - name: holiday
        description: Name of the holiday
        tests:
          - not_null
      - name: weekday
        description: Day of the week
        tests:
          - not_null
      - name: month
        description: Month part of the date
        tests:
          - not_null
      - name: day
        description: Day part of the date
        tests:
          - not_null
      - name: year
        description: Year part of the date
        tests:
          - not_null
    config:
      re_data_monitored: true
      re_data_time_filter: date
  - name: uscitypopdensity
    description: Cities with population and population density
    # columns: 
    #   - name: date
    #     description: Full date of the holiday
    #     tests:
    #       - not_null
    #   - name: holiday
    #     description: Name of the holiday
    #     tests:
    #       - not_null
    #   - name: weekday
    #     description: Day of the week
    #     tests:
    #       - not_null
    #   - name: month
    #     description: Month part of the date
    #     tests:
    #       - not_null
    #   - name: day
    #     description: Day part of the date
    #     tests:
    #       - not_null
    #   - name: year
    #     description: Year part of the date
    #     tests:
    #       - not_null
    config:
      re_data_monitored: true
  - name: DAYS_2016_2020
    description: Cities with population and population density
    config:
      re_data_monitored: true
  - name: hours
    description: Hours of the day with 15 min resolution
    config:
      re_data_monitored: true
