select EVENT_ID, TYPE, SEVERITY, CONVERT_TIMEZONE( 'UTC', TIME_ZONE , START_TIME_UTC_ ) as StartTime,
       CONVERT_TIMEZONE( 'UTC', TIME_ZONE , END_TIME_UTC_ ) as EndTime, LOCATION_LAT, LOCATION_LNG,
       AIRPORT_CODE, CITY, COUNTY, STATE, ZIP_CODE from {{source ('weather_events', 'US_WEATHER_EVENTS_RAW')}}